


const songData: any[] = [
  {
    id: "shes-on-fire",
    name: "She's on Fire",
    artist: "Amy Holland",
    album: "Scarface",
    year: "1983",
    img: "https://mendoza-showcase.s3.us-west-2.amazonaws.com/music-player-react/album_covers/shes-on-fire.jpg",
    mp3: "https://mendoza-showcase.s3.us-west-2.amazonaws.com/music-player-react/music/shes-on-fire.mp3",
  },
  {
    id: "out-of-touch",
    name: "Out of Touch",
    artist: "Hall & Oates",
    album: "Big Bam Boom",
    year: "1984",
    img: "https://mendoza-showcase.s3.us-west-2.amazonaws.com/music-player-react/album_covers/out-of-touch.jpg",
    mp3: "https://mendoza-showcase.s3.us-west-2.amazonaws.com/music-player-react/music/out-of-touch.mp3",
  },
  // {
  //   id: "tears-for-fears",
  //   name: "Everybody Wants to Rule the World",
  //   artist: "Tears for Fears",
  //   album: "Songs from the Big Chair",
  //   year: "1985",
  //   img: "https://mendoza-showcase.s3.us-west-2.amazonaws.com/music-player-react/album_covers/tears-for-fears.jpg",
  //   mp3: "https://mendoza-showcase.s3.us-west-2.amazonaws.com/music-player-react/music/tears-for-fears.mp3",
  // },
  {
    id: "rush-rush",
    name: "Rush Rush",
    artist: "Debbie Harry",
    album: "Scarface",
    year: "1983",
    img: "https://mendoza-showcase.s3.us-west-2.amazonaws.com/music-player-react/album_covers/rush-rush.jpg",
    mp3: "https://mendoza-showcase.s3.us-west-2.amazonaws.com/music-player-react/music/rush-rush.mp3",
  },
  {
    id: "boys-dont-cry",
    name: "Boys Don't Cry",
    artist: "The Cure",
    album: "Boys Don't Cry",
    year: "1978",
    img: "https://mendoza-showcase.s3.us-west-2.amazonaws.com/music-player-react/album_covers/boys-dont-cry.jpg",
    mp3: "https://mendoza-showcase.s3.us-west-2.amazonaws.com/music-player-react/music/boys-dont-cry.mp3",
  },
  {
    id: "dont-stop-me-now",
    name: "Don't Stop Me Now",
    artist: "Queen",
    album: "Jazz",
    year: "1978",
    img: "https://mendoza-showcase.s3.us-west-2.amazonaws.com/music-player-react/album_covers/dont-stop-me-now.jpg",
    mp3: "https://mendoza-showcase.s3.us-west-2.amazonaws.com/music-player-react/music/dont-stop-me-now.mp3",
  },
  {
    id: "never-gonna-give-you-up",
    name: "Never Gonna Give You Up",
    artist: "Rick Astley",
    album: "Whenever You Need Somebody",
    year: "1987",
    img: "https://mendoza-showcase.s3.us-west-2.amazonaws.com/music-player-react/album_covers/never-gonna-give-you-up.jpg",
    mp3: "https://mendoza-showcase.s3.us-west-2.amazonaws.com/music-player-react/music/never-gonna-give-you-up.mp3",
  },
  {
    id: "rasputin",
    name: "Rasputin",
    artist: "Boney M",
    album: "Nightflight to Venus",
    year: "1978",
    img: "https://mendoza-showcase.s3.us-west-2.amazonaws.com/music-player-react/album_covers/rasputin.jpg",
    mp3: "https://mendoza-showcase.s3.us-west-2.amazonaws.com/music-player-react/music/rasputin.mp3",
  },
  {
    id: "take-on-me",
    name: "Take On Me",
    artist: "A-ha",
    album: "Hunting High and Low",
    year: "1984",
    img: "https://mendoza-showcase.s3.us-west-2.amazonaws.com/music-player-react/album_covers/take-on-me.jpg",
    mp3: "https://mendoza-showcase.s3.us-west-2.amazonaws.com/music-player-react/music/take-on-me.mp3",
  },
  {
    id: "west-end-girls",
    name: "West End Girls",
    artist: "The Pet Shop Boys",
    album: "Please",
    year: "1986",
    img: "https://mendoza-showcase.s3.us-west-2.amazonaws.com/music-player-react/album_covers/west-end-girls.jpg",
    mp3: "https://mendoza-showcase.s3.us-west-2.amazonaws.com/music-player-react/music/west-end-girls.mp3",
  },
  {
    id: "what-is-love",
    name: "What is Love",
    artist: "Haddaway",
    album: "The Album",
    year: "1993",
    img: "https://mendoza-showcase.s3.us-west-2.amazonaws.com/music-player-react/album_covers/what-is-love.jpg",
    mp3: "https://mendoza-showcase.s3.us-west-2.amazonaws.com/music-player-react/music/what-is-love.mp3",
  },
  {
    id: "where-is-my-mind",
    name: "Where is My Mind?",
    artist: "Pixies",
    album: "Surfer Rosa",
    year: "1988",
    img: "https://mendoza-showcase.s3.us-west-2.amazonaws.com/music-player-react/album_covers/where-is-my-mind.jpg",
    mp3: "https://mendoza-showcase.s3.us-west-2.amazonaws.com/music-player-react/music/where-is-my-mind.mp3",
  },
  {
    id: "turn-out-the-night",
    name: "Turn Out the Night",
    artist: "Amy Holland",
    album: "Scarface",
    year: "1983",
    img: "https://mendoza-showcase.s3.us-west-2.amazonaws.com/music-player-react/album_covers/turn-out-the-night.jpg",
    mp3: "https://mendoza-showcase.s3.us-west-2.amazonaws.com/music-player-react/music/turn-out-the-night.mp3",
  },
  {
    id: "just-cant-get-enough",
    name: "Just Can't Get Enough",
    artist: "Depeche Mode",
    album: "Catching Up with Depeche Mode",
    year: "1985",
    img: "https://mendoza-showcase.s3.us-west-2.amazonaws.com/music-player-react/album_covers/just-cant-get-enough.jpg",
    mp3: "https://mendoza-showcase.s3.us-west-2.amazonaws.com/music-player-react/music/just-cant-get-enough.mp3",
  },
];

export { songData };
